
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/allen_vote?serverTimezone=GMT%2B8&useSSL=FALSE
    username: root
    password: 1234567890
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    database: 1
    host: 114.132.239.110
    port: 6379
    password:
    #超时时间：单位ms
    timeout: 60000
    lettuce:
      cluster:
        refresh:
          adaptive: true
          period: 20


# mybatis-plus相关配置
mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  global-config:
    db-config:
      id-type: auto
      field-strategy: NOT_EMPTY
      db-type: MYSQL
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



